version: '3'
services:
 reverseproxy:
    container_name: reverseproxy
    build: .
    image: nginx
    volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
            - "80:80"
    networks:
      allnetwork:
        ipv4_address: 172.20.0.5

networks:
    default:
       external:
          name: allnetwork
    allnetwork:
      external: true